import "server-only";

import { createHash } from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import { createMarketingServiceClient } from "@/lib/marketing/db";
import { deriveContentStatus } from "@/features/studio-v2/policy.mjs";
import type { CreativeReferenceContext } from "./creative-context";
import type { VideoDatabase } from "@/types/video-database";

const MAX_REMOTE_ASSET_BYTES = 150 * 1024 * 1024;

function extensionFor(contentType: string, outputKind: "image" | "video") {
  if (contentType.includes("webp")) return "webp";
  if (contentType.includes("jpeg") || contentType.includes("jpg")) return "jpg";
  if (contentType.includes("png")) return "png";
  if (contentType.includes("webm")) return "webm";
  if (contentType.includes("quicktime")) return "mov";
  return outputKind === "image" ? "png" : "mp4";
}

async function findGeneratedAsset(db: SupabaseClient<VideoDatabase>, ownerId: string, generationRunId: string) {
  const { data, error } = await db.from("media_assets")
    .select("*")
    .eq("owner_id", ownerId)
    .contains("metadata", { marketing_generation_run_id: generationRunId })
    .limit(1)
    .maybeSingle();
  if (error) throw new Error(error.message);
  return data;
}

export async function storeRemoteMarketingAsset(input: {
  db: SupabaseClient<VideoDatabase>;
  ownerId: string;
  generationRunId: string;
  campaignId: string | null;
  releaseId: string | null;
  contentItemId: string;
  provider: string;
  model: string;
  remoteUrl: string;
  outputKind: "image" | "video";
  assetType: "social_image" | "content_video";
  context: CreativeReferenceContext;
}) {
  let asset = await findGeneratedAsset(input.db, input.ownerId, input.generationRunId);
  if (!asset) {
    const response = await fetch(input.remoteUrl, { cache: "no-store" });
    if (!response.ok) throw new Error(`Could not download generated marketing asset (${response.status}).`);
    const length = Number(response.headers.get("content-length") || 0);
    if (length > MAX_REMOTE_ASSET_BYTES) throw new Error("Generated marketing asset exceeds the Media Library import limit.");
    const buffer = Buffer.from(await response.arrayBuffer());
    if (!buffer.length || buffer.length > MAX_REMOTE_ASSET_BYTES) throw new Error("Generated marketing asset is empty or too large.");

    const contentType = response.headers.get("content-type")?.split(";")[0] || (input.outputKind === "image" ? "image/png" : "video/mp4");
    const extension = extensionFor(contentType, input.outputKind);
    const bucket = "public-media";
    const path = `${input.ownerId}/library/marketing/${input.generationRunId}.${extension}`;
    const { error: uploadError } = await input.db.storage.from(bucket).upload(path, buffer, {
      contentType,
      cacheControl: "31536000",
      upsert: false,
    });
    if (uploadError && !uploadError.message.toLowerCase().includes("already exists")) throw new Error(uploadError.message);
    const publicUrl = input.db.storage.from(bucket).getPublicUrl(path).data.publicUrl;
    const hash = createHash("sha256").update(buffer).digest("hex");
    const referenceAssetIds = [...new Set([
      ...input.context.imageReferences,
      ...input.context.videoReferences,
      ...input.context.identityAssets,
    ].map((reference) => reference.assetId).filter((id): id is string => Boolean(id)))];
    const referenceUrls = [...new Set([
      ...input.context.imageReferences,
      ...input.context.videoReferences,
    ].map((reference) => reference.url))];
    const { data, error } = await input.db.from("media_assets").insert({
      owner_id: input.ownerId,
      bucket_name: bucket,
      storage_path: path,
      public_url: publicUrl,
      asset_type: input.assetType,
      mime_type: contentType,
      file_size: buffer.length,
      content_hash: hash,
      visibility: "public",
      metadata: {
        original_name: `${input.generationRunId}.${extension}`,
        title: `Atlas AI creative for ${input.context.release.title}`,
        description: "Generated by Atlas Irwin Creative Engine from release and brand visual lineage.",
        tags: ["atlas-generated", "marketing", "creative-lineage", "approval-required"],
        upload_source: input.provider,
        source_kind: "generated",
        provider: input.provider,
        model: input.model,
        provider_source_url: input.remoteUrl,
        marketing_generation_run_id: input.generationRunId,
        campaign_id: input.campaignId,
        release_id: input.releaseId,
        content_item_id: input.contentItemId,
        reference_asset_ids: referenceAssetIds,
        reference_urls: referenceUrls,
        release_artwork_url: input.context.release.artworkUrl,
        cohesion_context_score: input.context.cohesionScore,
        reference_summary: input.context.referenceSummary,
      },
    }).select("*").single();
    if (error) {
      if (error.code === "23505") {
        asset = await findGeneratedAsset(input.db, input.ownerId, input.generationRunId);
      } else {
        throw new Error(error.message);
      }
    } else {
      asset = data;
    }
  }
  if (!asset?.public_url) throw new Error("Generated marketing asset could not be registered with a public Media Library URL.");

  const { error: demoteError } = await input.db.from("media_links")
    .update({ is_primary: false })
    .eq("owner_id", input.ownerId)
    .eq("content_item_id", input.contentItemId)
    .eq("role", input.assetType);
  if (demoteError) throw new Error(demoteError.message);
  const { data: existingLink, error: existingLinkError } = await input.db.from("media_links")
    .select("id")
    .eq("owner_id", input.ownerId)
    .eq("content_item_id", input.contentItemId)
    .eq("media_asset_id", asset.id)
    .eq("role", input.assetType)
    .limit(1)
    .maybeSingle();
  if (existingLinkError) throw new Error(existingLinkError.message);
  const linkRow = {
    owner_id: input.ownerId,
    media_asset_id: asset.id,
    content_item_id: input.contentItemId,
    release_id: null,
    track_id: null,
    role: input.assetType,
    is_primary: true,
    caption: "Generated by Atlas Creative Engine",
  };
  const { error: linkError } = existingLink
    ? await input.db.from("media_links").update(linkRow).eq("id", existingLink.id)
    : await input.db.from("media_links").insert(linkRow);
  if (linkError) throw new Error(linkError.message);

  const marketing = createMarketingServiceClient();
  const { data: content, error: contentError } = await marketing.from("content_items")
    .select("*")
    .eq("id", input.contentItemId)
    .eq("owner_id", input.ownerId)
    .single();
  if (contentError || !content) throw new Error(contentError?.message || "Content item not found while attaching generated creative.");
  const status = deriveContentStatus({
    current: content.status,
    publishedAt: content.published_at,
    scheduledAt: content.scheduled_at,
    assetUrl: asset.public_url,
    caption: content.caption,
    hook: content.hook_text,
  });
  const { error: updateError } = await marketing.from("content_items").update({
    asset_url: asset.public_url,
    status,
    source: "ai",
    approval_status: "pending",
    generated_from_run_id: input.generationRunId,
  }).eq("id", input.contentItemId).eq("owner_id", input.ownerId);
  if (updateError) throw new Error(updateError.message);

  return { asset, status };
}
