import "server-only";

import { createHash } from "node:crypto";
import type { VideoDatabase } from "@/types/video-database";
import type { SupabaseClient } from "@supabase/supabase-js";

const MAX_REMOTE_ASSET_BYTES = 150 * 1024 * 1024;

type LineageKey = "generation_id" | "render_id" | "thumbnail_candidate_id";

async function findLineageAsset(
  db: SupabaseClient<VideoDatabase>,
  ownerId: string,
  key: LineageKey,
  value: string,
) {
  const result = await db.from("media_assets")
    .select("*")
    .eq("owner_id", ownerId)
    .contains("metadata", { [key]: value })
    .limit(1)
    .maybeSingle();
  if (result.error) throw new Error(result.error.message);
  return result.data;
}

export async function storeRemoteGeneratedAsset(input: {
  db: SupabaseClient<VideoDatabase>;
  ownerId: string;
  projectId: string;
  shotId?: string | null;
  generationId: string;
  provider: string;
  model: string;
  remoteUrl: string;
  assetType: "storyboard_frame" | "video_reference" | "shot_preview" | "shot_final" | "thumbnail";
}) {
  const existing = await findLineageAsset(input.db, input.ownerId, "generation_id", input.generationId);
  if (existing) return existing;

  const response = await fetch(input.remoteUrl, { cache: "no-store" });
  if (!response.ok) throw new Error(`Could not download generated asset (${response.status}).`);
  const length = Number(response.headers.get("content-length") || 0);
  if (length > MAX_REMOTE_ASSET_BYTES) throw new Error("Generated asset exceeds the Media Library import limit.");
  const buffer = Buffer.from(await response.arrayBuffer());
  if (!buffer.length || buffer.length > MAX_REMOTE_ASSET_BYTES) throw new Error("Generated asset is empty or too large.");

  const contentType = response.headers.get("content-type")?.split(";")[0] ||
    (input.assetType === "storyboard_frame" || input.assetType === "thumbnail" ? "image/png" : "video/mp4");
  const extension = contentType.includes("webm") ? "webm" : contentType.startsWith("image/") ? (contentType.includes("jpeg") ? "jpg" : "png") : "mp4";
  const bucket = "public-media";
  const path = `${input.ownerId}/library/video-director/${input.projectId}/${input.generationId}.${extension}`;
  const { error: uploadError } = await input.db.storage.from(bucket).upload(path, buffer, {
    contentType,
    cacheControl: "31536000",
    upsert: false,
  });
  if (uploadError && !uploadError.message.toLowerCase().includes("already exists")) throw new Error(uploadError.message);
  const publicUrl = input.db.storage.from(bucket).getPublicUrl(path).data.publicUrl;
  const hash = createHash("sha256").update(buffer).digest("hex");
  const { data, error } = await input.db.from("media_assets").insert({
    owner_id: input.ownerId,
    bucket_name: bucket,
    storage_path: path,
    public_url: publicUrl,
    asset_type: input.assetType,
    mime_type: contentType,
    file_size: buffer.length,
    content_hash: hash,
    visibility: "public",
    metadata: {
      original_name: `${input.generationId}.${extension}`,
      title: input.shotId ? `Generated shot ${input.shotId}` : "Video Director reference",
      description: "Generated by Atlas Video Director",
      tags: ["video-director", input.provider, input.model],
      upload_source: input.provider,
      source_kind: "generated",
      project_id: input.projectId,
      shot_id: input.shotId ?? null,
      generation_id: input.generationId,
      provider: input.provider,
      model: input.model,
      provider_source_url: input.remoteUrl,
    },
  }).select("*").single();
  if (error) {
    if (error.code === "23505") {
      const raced = await findLineageAsset(input.db, input.ownerId, "generation_id", input.generationId);
      if (raced) return raced;
    }
    throw new Error(error.message);
  }
  if (!data) throw new Error("Could not register generated media asset.");
  return data;
}

export async function registerWorkerRenderAsset(input: {
  db: SupabaseClient<VideoDatabase>;
  ownerId: string;
  projectId: string;
  renderId: string;
  bucket: string;
  path: string;
  publicUrl: string;
  renderType: string;
  result: Record<string, unknown>;
}) {
  const existing = await findLineageAsset(input.db, input.ownerId, "render_id", input.renderId);
  if (existing) return existing;

  const assetType = input.renderType === "master_16_9" ? "music_video_master" : "social_cut";
  const number = (key: string) => typeof input.result[key] === "number" ? input.result[key] as number : null;
  const { data, error } = await input.db.from("media_assets").insert({
    owner_id: input.ownerId,
    bucket_name: input.bucket,
    storage_path: input.path,
    public_url: input.publicUrl,
    asset_type: assetType,
    mime_type: "video/mp4",
    file_size: number("file_size"),
    content_hash: null,
    width: number("width"),
    height: number("height"),
    duration_ms: number("duration_ms"),
    visibility: "public",
    metadata: {
      original_name: `${input.renderType}.mp4`,
      title: input.renderType.replaceAll("_", " "),
      description: "Rendered by Atlas Video Director media worker",
      tags: ["video-director", "render", input.renderType],
      upload_source: "atlas_media_worker",
      source_kind: "render",
      project_id: input.projectId,
      render_id: input.renderId,
    },
  }).select("*").single();
  if (error) {
    if (error.code === "23505") {
      const raced = await findLineageAsset(input.db, input.ownerId, "render_id", input.renderId);
      if (raced) return raced;
    }
    throw new Error(error.message);
  }
  if (!data) throw new Error("Could not register rendered media asset.");
  return data;
}

export async function registerWorkerThumbnailAsset(input: {
  db: SupabaseClient<VideoDatabase>;
  ownerId: string;
  projectId: string;
  candidateId: string;
  bucket: string;
  path: string;
  publicUrl: string;
  timestampMs: number;
  sourceAssetId: string;
  result: Record<string, unknown>;
}) {
  const existing = await findLineageAsset(input.db, input.ownerId, "thumbnail_candidate_id", input.candidateId);
  if (existing) return existing;
  const number = (key: string) => typeof input.result[key] === "number" ? input.result[key] as number : null;
  const { data, error } = await input.db.from("media_assets").insert({
    owner_id: input.ownerId,
    bucket_name: input.bucket,
    storage_path: input.path,
    public_url: input.publicUrl,
    asset_type: "thumbnail",
    mime_type: "image/jpeg",
    file_size: number("file_size"),
    content_hash: null,
    width: number("width"),
    height: number("height"),
    duration_ms: null,
    visibility: "public",
    metadata: {
      original_name: `thumbnail-${input.candidateId}.jpg`,
      title: `Thumbnail candidate ${Math.round(input.timestampMs / 1000)}s`,
      description: "Still extracted from the final Atlas Video Director master",
      tags: ["video-director", "thumbnail", "still"],
      upload_source: "atlas_media_worker",
      source_kind: "extracted_frame",
      project_id: input.projectId,
      thumbnail_candidate_id: input.candidateId,
      source_master_asset_id: input.sourceAssetId,
      timestamp_ms: input.timestampMs,
      selected_thumbnail: false,
    },
  }).select("*").single();
  if (error) {
    if (error.code === "23505") {
      const raced = await findLineageAsset(input.db, input.ownerId, "thumbnail_candidate_id", input.candidateId);
      if (raced) return raced;
    }
    throw new Error(error.message);
  }
  if (!data) throw new Error("Could not register thumbnail candidate.");
  return data;
}
