import {
  FiActivity,
  FiBarChart2,
  FiCalendar,
  FiDisc,
  FiFeather,
  FiGlobe,
  FiHome,
  FiImage,
  FiLayers,
  FiLogOut,
  FiMonitor,
  FiMusic,
  FiMail,
  FiPlus,
  FiRadio,
  FiUsers,
} from "react-icons/fi";
export const studioIcons = {
  dashboard: FiHome,
  releases: FiDisc,
  distribution: FiGlobe,
  sites: FiMonitor,
  musicLab: FiMusic,
  content: FiFeather,
  calendar: FiCalendar,
  outreach: FiUsers,
  analytics: FiBarChart2,
  soundcloud: FiMusic,
  spotify: FiRadio,
  brand: FiActivity,
  campaigns: FiLayers,
  media: FiImage,
  dataHealth: FiActivity,
  plus: FiPlus,
  logout: FiLogOut,
  mail: FiMail,
};
