import {
  FiActivity,
  FiBarChart2,
  FiCalendar,
  FiCheckSquare,
  FiDisc,
  FiFeather,
  FiHome,
  FiImage,
  FiLayers,
  FiLogOut,
  FiMusic,
  FiMail,
  FiPlus,
  FiRadio,
  FiSliders,
  FiUsers,
} from "react-icons/fi";
export const studioIcons = {
  dashboard: FiHome,
  releases: FiDisc,
  content: FiFeather,
  calendar: FiCalendar,
  outreach: FiUsers,
  analytics: FiBarChart2,
  soundcloud: FiMusic,
  spotify: FiRadio,
  brand: FiSliders,
  campaigns: FiLayers,
  media: FiImage,
  dataHealth: FiActivity,
  tasks: FiCheckSquare,
  plus: FiPlus,
  logout: FiLogOut,
  mail: FiMail,
};
